apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: challenge-local-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: challenge.local
    http:
      paths:
      - path: /
        backend:
          serviceName: challenge-local-app
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-local-app
  labels:
    app: challenge-local-app
    tier: frontend
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    app: challenge-local-app
    tier: frontend
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-local-app
  labels:
    app: challenge-local-app
spec:
  selector:
    matchLabels:
      app: challenge-local-app
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: challenge-local-app
        tier: frontend
    spec:
      containers:
      - name: challenge-local-app
        image: challenge_local
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
